name: notification_system
description: A comprehensive notification handling package for Flutter, supporting Firebase, Local Notifications, and In-App messaging.
version: 0.0.1
homepage: https://github.com/Ahmed-Alkamel/notification_system
repository: https://github.com/Ahmed-Alkamel/notification_system
issue_tracker: https://github.com/Ahmed-Alkamel/notification_system/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0
  injectable: ^2.7.1+4
  get_it: ^9.2.0
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  overlay_support: ^2.1.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.11.0
  freezed: ^3.2.5
  json_serializable: ^6.12.0
  injectable_generator: ^2.12.0
flutter:


